"""Generate the audit finding catalog and field-by-field evidence appendices."""
import json
from pathlib import Path

root = Path(__file__).parent
repo = root.parent
S = "vendoo-studio/server/vendoo_studio/"
F = "vendoo-studio/src/"
E = "vendoo-extension/"
# id, severity, group, title, rate, preconditions, steps, expected, actual,
# source, cause, impact/risk, evidence, automated regression, manual regression
findings = [
("C01", "High", "Code defects — security", "Pairing accepts a fixed bypass and stores a weak token with broad permissions", "1/1 isolated bypass probe; file mode observed once", "Current ExtensionManager and initialized local data directory", "Call verify_token with the literal direct in an isolated process; inspect token-file mode without reading its contents.", "Only a strong, authorized pairing credential is accepted; token file restricted to the current user.", "verify_token returned true for direct. Generated token is eight hex characters; actual file mode was 0644.", S+"routes/extension.py:74", "verify_token's unconditional direct fallback at line 92 bypasses generated credentials; normal open() inherits permissive umask; generation truncates UUID at line 82.", "Unauthorized local/browser pairing could gain automation/data access. No exploit against the real session was performed; publication risk depends on downstream messages.", "isolated-probes.json", "Reject direct/random/empty tokens; require strong token entropy and 0600 persistence.", "Pair a current extension, reject an unapproved controller, and confirm the legitimate connection still works."),
("C02", "High", "Code defects — security", "WebSocket connection can displace paired client before authentication", "Static path confirmed; hostile browser exploit not attempted", "Reachable local WebSocket endpoint", "Inspect WebSocket accept, replacement, and authentication ordering; inspect pairing-token route.", "Authenticate and enforce Origin before replacing a paired connection; expose pairing credentials only through an authorized flow.", "Connection accepted and previous socket closed before authentication; no Origin check in the reviewed handler; pairing-token route returns a token without API authentication.", S+"routes/extension.py:380", "Handler lines 411–421 accepts/replaces first; token and WebSocket trust boundaries are inconsistent.", "Potential denial of service and unauthorized access; runtime exploitability from hostile origins remains untested.", "isolated-probes.json", "Untrusted origins/unauthenticated sockets cannot replace a paired client or obtain credentials.", "Attempt an unpaired connection in an isolated browser and verify the active extension remains paired."),
("C03", "High", "Code defects — security", "Packaged update path lacks verified artifact integrity and removes quarantine", "Static review; no update installed", "Packaged update available", "Trace downloaded zip through extraction, preparation, and app replacement.", "Verify the downloaded bytes and trusted signing identity before running or replacing an app.", "Reviewed path downloads then extracts without a digest/signature verification; preparation invokes xattr -cr.", S+"services/packaged_updates.py:247", "Download/extract at 247–249 is not bound to verified artifact bytes; _prepare_app_bundle at 167–179 removes quarantine.", "Compromised distribution could execute code as the user. No download was installed during this audit.", "source review only", "Reject modified, unsigned, incorrectly signed and path-escaping archives before replacement.", "Use a trusted test release and a tampered copy in an isolated install; verify only the trusted bundle can launch."),
("C04", "High", "Code defects — data integrity", "Invalid nested JSON is persisted before validation crashes", "1/1 isolated write/read sequence; two validator exception cases", "Disposable conversation with valid listing revision", "PUT listing with ebay_specifics set to a string; GET the listing afterward.", "Return a clear validation error without changing the last valid revision.", "PUT returned 500 and subsequent GET also returned 500; validator invokes .get on a string after persistence.", S+"routes/listings.py:82", "Raw revision saved before validate_listing; models/validation.py:58–60 assumes nested mappings even after Pydantic errors.", "Listing editor becomes unreadable; persistent data corruption until recovered. No real user listing was poisoned.", "isolated-probes.json; validation-matrix.json", "Malformed nested object types return 422/400 and retain identical current revision; GET remains 200.", "Apply malformed typed JSON to a disposable listing and reload; confirm prior valid content remains."),
("C05", "High", "Code defects — data integrity", "Revision restore accepts a revision from another conversation", "1/1 isolated cross-conversation restore", "Two disposable conversations and a revision belonging only to A", "POST B/revisions/<A revision>/restore; read B.", "Reject a revision whose conversation does not match the URL.", "HTTP 200 copied A's listing into B.", S+"routes/listings.py:155", "Revision fetched by global ID without verifying conversation ownership before save.", "Cross-listing data contamination; no unrelated real listing was touched.", "isolated-probes.json", "Cross-conversation restore returns 404/403 and leaves both revisions unchanged.", "Attempt a mismatched revision restore using disposable fixtures and verify both listings."),
("C06", "High", "Code defects — data integrity", "Learned-field backfill mutates approved snapshots and changes array types", "Observed across primary job backfill; one existing value changed type", "Approved job, later discovered marketplace fields", "Compare approved revision with source after job schema discovery; trace backfill assignments.", "Approved job JSON is immutable; metadata discovery preserves existing values/types.", "28 empty learned keys added and etsy_specifics.materials changed from [] to empty string; job.listing_snapshot is reassigned to backfilled latest listing.", S+"services/fill_log.py:590", "Backfill assigns job.listing_snapshot at line 596. RegistryService.merge_learned_fields at registry.py:459–465 treats empty arrays as missing and writes an empty string.", "Approved data can change during execution and arrays are corrupted; subsequent retries may send different content.", "source-changes-after-jobs.json; approved-studio-snapshot.json; job-eb8bad1d1e1f-snapshot.json", "Hash approved snapshot through schema events and later editor writes; preserve []/false/0/null distinctly.", "Approve a draft, discover fields while editing another revision, and compare the executed snapshot with approval."),
("C07", "High", "Code defects — recovery", "Retry bypasses validation and the one-active-job guard", "1/1 isolated retry sequence; new-job guard correctly rejected second create", "Failed job A and queued job B; A edited to blank title", "Create A; mark its isolated job failed; create B; blank A's title; POST A/retry.", "Reject while B is active and reject invalid latest data; approval remains explicit.", "Retry returned 200; two jobs were active/queued and A's listing title was blank. Initial second create correctly returned 409.", S+"routes/jobs.py:591", "Retry resets status/snapshot from latest revision at 614–632 without reusing create_job validation and active guard.", "Concurrent automation and invalid data can enter jobs; duplicate/conflicting browser actions possible. No concurrent real automation was run.", "concurrency-probes.json", "Every create/retry/repair entry point enforces atomic active-job and validation checks.", "With one disposable job active, retry another; verify rejection and unchanged approved snapshot."),
("C08", "High", "Code defects — draft workflow", "Schema-probe draft binding causes all photos to be skipped", "All full updates of primary draft; final 0/5 photos", "Generation has automatically created a category-only schema draft; five Studio photos", "Generate listing, let schema probe bind item, then confirm Send/Update; reopen saved draft.", "Upload and verify all five approved photos even when reusing a photo-empty probe draft.", "Every normal update reused the item ID and skipped upload; final General images array is empty.", S+"routes/extension.py:219", "skipPhotos is true for any reuse_existing binding; background.js:1676–1681 also returns when item ID exists without checking photo inventory.", "Incomplete real draft despite completed stages; no photo-order acceptance possible.", "final-saved-draft.json; final-eb8bad1d1e1f-events.json; photo-metadata.json", "Probe-created empty draft followed by send uploads exactly five ordered photos and verifies persistence.", "Generate a new five-photo fixture, send once, reopen by ID, and compare all photos visually."),
("C09", "High", "Code defects — draft workflow", "New route name is accepted as a saved Vendoo item ID", "1/1 ordinary new-item Send attempt", "Second fixture with five photos and no existing Vendoo binding", "Send once; inspect saving_general event and Open Listing binding.", "Wait for durable non-new item ID and successfully reopen it before reporting saved.", "Saved ID was new and URL /app/item/new; subsequent readback reported missing item ID.", E+"content-scripts/vendoo.js:4368", "Content-script extractItemId accepts any /item/ segment, unlike background.js:839–845 which rejects new. saveGeneral trusts it after a fixed delay.", "No reliable draft identity, unsafe retry/deduplication and possible abandoned draft; actual duplicate not established.", "manual-job-timeline.json; final-0093f5d1dd0f-events.json", "Reject new/empty IDs; wait for persisted ID and verify GET/reopen before binding or completion.", "Ordinary new-item Send with slow uploads/save; confirm a durable ID and reopened photos before success."),
("C10", "High", "Code defects — extension", "eBay and Depop marketplace activation fails on accessible forms", "eBay 3/3 attempted fills across two fixtures; Depop 1/1 isolated fill", "Signed-in Vendoo, saved audit draft, current extension", "Run all-platform job and retry eBay; select Depop only and update; manually navigate same draft to the corresponding form.", "Activate the mounted marketplace form and proceed with required specifics.", "Could not activate ebay/depop marketplace section; forms were accessible through manual navigation.", E+"content-scripts/vendoo.js:4296", "Likely timing/visibility/first-matching-nav assumptions in activateMarketplaceSection, sectionLooksActive and readiness checks (4173, 4226, 4296–4336); exact failing DOM predicate not instrumented.", "eBay/Depop draft incomplete; first platform failure prevents later platforms in a combined run.", "final-eb8bad1d1e1f-events.json; final-0093f5d1dd0f-events.json; vendoo-ebay-inputs.json; depop-after-attempt.json", "Test real async mounted/offscreen/duplicate nav elements; wait for correct form identity, not initial visibility alone.", "Start at General and each other marketplace tab, then fill eBay/Depop with slow loading and verify saved specifics."),
("C11", "High", "Code defects — verification", "Audit stages and completion do not verify saved accuracy", "Schema plus three isolated marketplace completions; all lacked photos", "Current draft pipeline", "Observe completed audit stages, then reopen the item and compare against approved snapshot.", "Any missing required photo/field or mismatched value fails acceptance; audit details reach Studio.", "General/marketplace audit returns ok despite omissions; completed Etsy/Posh/Mercari had inaccurate or missing fields.", E+"content-scripts/vendoo.js:4102", "auditGeneral checks six fields and returns ok true (4129); marketplace audit at 4340–4365 also returns ok on missing controls. Background step payload at 588–595 drops audit fields.", "False success can cause a user to trust an incomplete listing. Publication was not observed.", "final-saved-draft.json; final-eb8bad1d1e1f-events.json", "Mutate one saved field/photo at a time; completion must fail and show expected/actual differences.", "Independently reopen every completed draft and compare all photos, required fields and publication statuses."),
("C12", "High", "Code defects — validation", "Marketplace and canonical constraints are largely unenforced", "46 cases: 37 accepted, 7 blocked, 2 exceptions", "Approved fixture independently modified one field per case", "Run validation-matrix.py and compare canonical enums, required fields, eligibility and title rules.", "Reject invalid selected-marketplace payloads with one precise field error before snapshot/dispatch.", "Whitespace/81-character titles, bad categories/dimensions, missing facts, invalid Depop/Etsy values and modern Etsy eligibility were accepted; eBay checks only four optional warnings.", S+"models/validation.py:21", "Pydantic schema is permissive; enum constants and dimensions regex in models/schema.py:18–44 are unused. Marketplace-specific validation is absent or warning-only.", "Invalid marketplace data enters approved snapshots and reaches draft workflows; evidence uncertainty receives no warning.", "validation-matrix.json; approved-studio-snapshot.json; 06-ready-with-unknown-facts.png", "Parameterize all requested validation cases and selected-platform boundaries; no exceptions on arbitrary JSON types.", "Independently corrupt each UI field, verify one actionable error, and verify extension receives no invalid snapshot."),
("C13", "Medium", "Code defects — upload", "Invalid image bytes are accepted when MIME claims image", "1/1 isolated spoofed upload", "Disposable conversation; file content not an image, MIME image/jpeg", "Upload twelve non-image bytes using image/jpeg and a traversal-shaped original filename.", "Reject undecodable image bytes; never trust supplied MIME alone.", "HTTP 200, dimensions null; bytes saved under safe random name. Tested path did not escape photo directory.", S+"services/photos.py:26", "Allowed MIME returns early; Pillow decode failure at 59 is ignored after writing the file.", "Broken photos reach generation/upload; arbitrary non-image bytes stored. Traversal was not reproduced.", "isolated-probes.json", "Reject invalid/truncated/spoofed images without stored records or bytes; retain legitimate supported formats.", "Upload renamed text as jpg and confirm clear rejection with no thumbnail/count change."),
("C14", "High", "Code defects — generation", "Ask Chat omits photos when history already contains editor messages", "1/1 initial exact-prompt attempt; later generation retry succeeded", "Five photos, manual listing revision, no prior analysis", "Create/edit listing before first photo analysis, then submit the exact supplied Ask Chat prompt.", "Analyze attached photos regardless of preceding editor-generated history.", "Assistant said photos were unavailable and requested brand/size/measurements despite five uploads.", S+"routes/chat.py:302", "_build_messages only analyzes when prior analysis exists or history length <=2 (313–319); prior revisions/messages can exceed that threshold. Structured notes are not passed to this analysis branch.", "Incorrect missing-evidence response and unnecessary user re-entry; generation depends on incidental history.", "05-chat-cannot-see-photos.png; listing-before-send.json", "First Ask Chat after manual revision still receives all photos and exact seller notes.", "Upload tag/ruler fixture, manually edit title, Ask Chat and verify visible tag facts without restating them."),
("C15", "Medium", "Code defects — chat", "Completed stream remains duplicated until reload", "Observed after initial Ask Chat and refinements; exact count not instrumented", "Chat response finishes and persists", "Send prompt; compare persisted assistant response with remaining streamed text; reload.", "One assistant response and cleared transient streaming content.", "Assistant answer appeared once as persisted content and again as residual stream; reload removed residual view.", F+"components/ChatPanel.tsx:467", "Controller cleared before stillMine check in completion paths (467–473 and 539–544), preventing intended stream cleanup.", "Misleading duplicate output; does not prove duplicate persisted assistant messages.", "05-chat-cannot-see-photos.png", "On successful persistence clear stream exactly once and render one message; reload preserves same count.", "Complete several refinements and verify no duplicated response before/after reload."),
("C16", "Medium", "Code defects — chat recovery", "Cancelled chat leaves conversation permanently In Progress", "1/1 live cancellation, status still in_progress after later reads", "Missing-field Ask Chat streaming on primary disposable listing", "Use Fields Ask Chat, cancel, reload/read conversation status after stream closes.", "Prompt restored and conversation returns to a settled non-generating status.", "Prompt restoration worked, but server conversation remained in_progress while no job was active and UI allowed input.", S+"routes/chat.py:548", "Cancelled streaming generator can exit before post-stream status reset at 569–588; cancellation cleanup is not in an outer finally.", "Misleading busy/listing status and unreliable recovery; input itself was preserved in this tested cancel path.", "ask-chat-missing-field-context.json; final-state.json", "Cancel before/after first token and disconnect SSE; assert status reset and database session closure.", "Cancel Ask Chat, reload, switch listings and return; verify recoverable prompt and accurate status."),
("C17", "High", "Code defects — chat recovery", "Missing-provider prompt is rejected before persistence", "1/1 isolated POST with unavailable provider", "No listing provider; user submits nonempty prompt", "POST messages with provider unavailable; fetch message history.", "Retain submitted prompt and provide direct Settings recovery; Retry restores correct action after reload.", "HTTP 400 instructed Settings, but messages remained empty. Frontend clears input before send and keeps retry text only in memory.", S+"routes/chat.py:539", "_require_provider runs before add_message at 543; ChatPanel.tsx:511 clears input and transient lastSendText cannot survive page reload.", "User-authored instructions can be lost on failure/reload.", "isolated-probes.json", "Provider validation failure persists/restores exact submitted prompt across reload; retries do not duplicate it.", "With provider unavailable, submit a long prompt, reload, reconnect provider and retry the original text."),
("C18", "High", "Code defects — diagnostic privacy", "Form diagnostics contain private account/address values", "Observed in real form/API inspection; sanitized in retained exports", "Signed-in account with saved shipping/address configuration", "Inspect output structure of draft form scraping, limiting review to key names and redacting values.", "Diagnostic exports omit account/address/credential fields by default and expose only listing-relevant evidence.", "Form data included local delivery address and location/profile fields; account filtering in discovered-field code did not cover every scraper/export path.", E+"content-scripts/vendoo.js:4450", "Generic scraping reads all listings.* controls including account fields; sanitization differs across collectMarketplaceSchemaFields and raw form scraping.", "Private account data can enter frontend diagnostics and exported logs/screenshots. No credential value was intentionally retained.", "final-saved-draft.json (redacted); source review", "Seed fake private address/token fields and assert absent from every diagnostic/frontend/export payload.", "Run Diagnose/Refresh with a test account and inspect sanitized export for private fields before sharing."),
("C19", "Medium", "Code defects — fill log", "DOM readback collapses arrays and misreads unchecked switches", "At least two multi-select arrays and two false switches compared", "Saved draft with tags arrays and Mercari switches false", "Compare final form scrape with saved API object and settled UI.", "Preserve all multi-select members, booleans and numeric zero.", "Form tags reported Woven instead of five members; smartPricing/smartOffers rendered on although saved API has false.", E+"content-scripts/vendoo.js:4467", "Reads .value instead of checkbox.checked and overwrites repeated name/id keys at 4472; no aggregation for multi-select hidden inputs.", "False filled/missing counts and incorrect repair context; underlying saved arrays/false values are intact in these cases.", "final-saved-draft.json; poshmark-after-save.json", "Readback fixtures with repeated input names, []/false/0/null; compare to saved values without string damage.", "Refresh a draft with multiple tags and unchecked switches; ensure Fields matches actual controls."),
("C20", "Medium", "Code defects — fill log", "Cached Fields are presented with live-source identity", "1/1 initial stale read; explicit Refresh corrected General values", "Probe cached blank draft, later full General save", "Open Fields after update without Refresh, compare to reopened draft, then Refresh.", "Invalidate stale cache or label its age/source accurately.", "Old blank title/price/dimensions persisted in Fields; cached response retained source api+form and no freshness metadata.", S+"routes/jobs.py:232", "Cached payload reuses original source; ListingEditor.tsx:99–106 prefetch uses staleTime Infinity without job-completion invalidation.", "Incorrect missing-field repairs may overwrite correct saved data; counts cannot be trusted.", "saved-draft-sanitized.json; final-saved-draft.json; job-fill-log.json", "Save changes after cached probe, then open Fields and require fresh data or explicit stale badge.", "Update General, reopen Fields without manual refresh and compare each field to Vendoo."),
("C21", "High", "Code defects — marketplace mapping", "Mercari resolves blouse to T-shirts", "1/1 saved Mercari category", "Notations short-sleeve button-front blouse, General Women/Tops", "Run Mercari-only save, reopen and inspect terminal category breadcrumb/API displayPath.", "Select an appropriate blouse/shirt terminal category or flag unresolved mapping.", "Saved Women > Tops & blouses > T-shirts (ID 161). Job completed.", E+"content-scripts/vendoo.js:2021", "Likely broad top/T-shirt synonym matching and default category resolution. Exact winning category candidate was not instrumented; General terminal validation does not detect platform semantic mismatch.", "Wrong category and dependent size/specifics, reduced listing accuracy.", "final-saved-draft.json; mercari-settled-after-save.json", "Category tests distinguish button-front blouse from knit tee using fixture evidence and each platform's terminal vocabulary.", "Send blouse and tee separately, reopen Mercari category and size options for both."),
("C22", "High", "Marketplace-policy issues", "Etsy save retains fabricated when-made and non-Draft configuration", "1/1 Etsy-only completed run and reopen", "Modern resale blouse; Etsy selected by later user instruction; approved when_made blank", "Send Etsy draft only; reopen When Made, Listing State and publication status.", "Do not invent eligibility/date; require Draft configuration and surface ineligibility before send.", "Made To Order persisted, listingState active/Live Listing, actual notListed true. No publication action observed.", E+"content-scripts/vendoo.js:3082", "No eligibility validation; blank when_made at 3122 skips clearing default; fillEtsyForm does not enforce listingState Draft.", "False item facts and unsafe future publication configuration. This is not evidence of an actual safety failure/publication.", "etsy-saved-When-Was-It-Made.json; etsy-saved-Listing-State.json; final-not-listed.json", "Modern resale fixture blocked/warned; unknown when-made cannot silently become made_to_order; every saved draft enforces Draft.", "Use modern validation fixture and separate eligible fixture; reopen configuration and actual NOT LISTED state."),
("C23", "Medium", "Code defects — marketplace mapping", "Platform-specific values are skipped or replaced by General defaults", "Poshmark color/tags and Etsy color/tags mismatches in reopened draft", "Approved platform-specific fields differ from General", "Save Poshmark/Etsy, reopen and compare colors, platform tags and title with approved object.", "Respect marketplace-specific overrides and report unresolvable live values clearly.", "Primary colors blank; Poshmark platform styleTags not preserved; Etsy five tags merged with General five; branded Etsy title remains.", E+"content-scripts/vendoo.js:3093", "Fillers prefer General colors/title/tags; Etsy explicitly merges both tag lists at 3124. Mapping does not consistently consume contract-specific fields.", "Completed drafts differ from approval; merged Etsy tags could exceed 13 on other fixtures (not reached here).", "approved-studio-snapshot.json; final-saved-draft.json", "Distinct General/platform overrides must survive send/readback; enforce tag limits after merges, or avoid merges.", "Use intentionally different approved platform tags/colors and compare saved forms exactly."),
("U01", "Medium", "UX defects", "Send appears enabled while invalid and errors are duplicated", "Live invalid editor plus repeated required-field matrix cases", "Missing title/description/price or other blocked values", "Open invalid listing, inspect button appearance, validation errors and click behavior.", "Disabled or clearly unavailable Send, one actionable error per field, focus/link to field.", "Green enabled-looking Send; click handler blocks, but duplicated required/Pydantic errors appear as combined text without clear focus targets.", F+"components/ListingEditor.tsx:664", "disabled only covers pending; click guards canSend at 666. validation.py:41 adds duplicate required errors after Pydantic.", "Confusing readiness and recovery; invalid-title click was not observed to dispatch.", "02-invalid-new-listing.png; 05-chat-cannot-see-photos.png; validation-matrix.json", "Disabled state matches can_send and one error per field; keyboard error activation focuses control.", "Clear required fields and use mouse/keyboard; confirm clear unavailable state and direct recovery."),
("U02", "Medium", "UX defects", "Unconfigured provider blocks drafting and still displays a model", "Static plus transient initial loading state; full logout UI not run", "Provider not configured or status pending", "Inspect create controls and ProviderStatus rendering with absent provider data.", "Manual draft creation remains usable; disconnected status explains provider setup without implying a model connection.", "Create disabled via providerConfigured; status defaults to mimo-v2.5-pro regardless of connection.", F+"app/App.tsx:74", "canCreate is tied to provider availability at 231; ProviderStatus.tsx:11–16 displays fallback model unconditionally.", "Manual workflow blocked unnecessarily and connection state misleading; persistent missing-provider UI remains a retest gap.", "isolated-probes.json; source review", "Render disconnected/pending/connected fixtures; manual creation works and model shown only with qualified connection status.", "Remove provider in isolated setup, create manual listing, and follow direct provider recovery."),
("U03", "Low", "UX defects", "Category and label placeholders resemble saved values", "Observed in both test listings", "Seller override fields are empty", "Inspect Category/Labels without typing; compare actual saved notes.", "Examples clearly distinct from populated values.", "Clothing >… and To List, A19 look populated though controls are empty.", F+"components/ItemDetails.tsx:92", "Concrete example placeholders styled like editable field content; default/example versus stored data is not visually explicit.", "Seller may assume category/labels have been saved; no direct data loss observed.", "05-chat-cannot-see-photos.png; layout-1280x800-verified.png", "Empty seller controls expose explicit empty state and never serialize placeholder content.", "Open untouched listing and distinguish examples from saved values without clicking fields."),
("U04", "Low", "UX defects", "Later editor tabs require undisclosed horizontal scrolling", "Three desktop sizes plus 390px mobile; tablet fits", "All five implemented marketplaces selected", "Inspect initial tab strip at requested exact viewport sizes; measure last tab bounding box.", "Visible affordance for more tabs or responsive layout that makes all tabs discoverable.", "JSON extends beyond editor/viewport initially; overflow scroll exists, scrollbar hidden.", F+"styles/app.css:2553", "Scrollable tab-group plus zero-height scrollbar at 2569; fixed narrow editor exposes no cue.", "Users miss JSON/later tabs; not proof of unreachable controls.", "layout-1280x800-verified.png; mobile-all-platform-tabs.png; tablet-editor-820x1180.png", "At all target sizes, each tab is discoverable and reachable through keyboard/touch with visible overflow cue.", "Find and activate every tab without prior knowledge of hidden horizontal scrolling."),
("U05", "Medium", "UX defects", "Mobile Settings has no reachable exit to listings", "1/1 at 390px; desktop recovery worked", "Mobile Settings open", "Tap Back to listings, inspect Settings sidebar; try Escape and visible controls.", "Back exits Settings and returns to listing list.", "Back opens Settings navigation; actual close-Settings button is in hidden footer. Escape only changes sidebar visibility.", F+"styles/app.css:3792", "Mobile hides sidebar-footer containing onCloseSettings (ListingSidebar.tsx:565–574); App.tsx:249 only sets mobileSidebarOpen.", "Mobile user trapped in Settings until reload/alternate navigation.", "mobile-settings-no-exit.png", "Mobile Settings exit visible and returns activeView to listings; keyboard/Escape contract explicit.", "On phone/iPad, open Settings, switch section, return to listings without reload."),
("U06", "Medium", "UX defects — accessibility", "Zoom restriction, focus hiding and field semantics impair accessibility", "One Lighthouse snapshot and one real aria-hidden console warning", "Desktop/mobile UI and current DOM", "Run snapshot audit; move between mobile sidebar/panes with focus retained; inspect viewport meta and field controls.", "Allow zoom, maintain visible focus outside aria-hidden content, valid roles and sufficient text contrast.", "maximum-scale=1; retained focus inside hidden sidebar; button role=listitem; job text contrast 4.41:1.", "vendoo-studio/index.html:5", "Viewport restriction plus mobile aria-hidden toggling in ListingSidebar.tsx:364; FillLogPanel button semantics and low-contrast styling.", "Low-vision/keyboard/assistive technology barriers; full screen-reader impact not tested.", "accessibility-failures.json; browser-console-final.txt", "axe/DOM checks and keyboard focus assertions at all viewports; allow 200% zoom and >=4.5 contrast.", "Zoom to 200%, navigate dialogs/sidebar/Fields by keyboard and screen reader without focus loss."),
("U07", "Medium", "UX defects — uploads", "Partial upload failure hides that a valid photo was saved", "1/1 live mixed batch; 1/1 isolated mixed batch", "One valid photo plus unsupported text in same UI upload", "Upload both files together; observe error and fetch photo list.", "Per-file outcomes or transactional rollback; successful photo count refreshed.", "HTTP 400 unsupported type but valid photo was already stored; UI presented batch error without explaining partial success.", S+"routes/photos.py:32", "Loop commits earlier photos before later failure; PhotoTray catch does not reconcile partial server result.", "Users may retry and create duplicates or misread photo counts; duplicate creation itself not tested.", "isolated-probes.json; ui-unsupported-upload.json; final-842b7f1762be-photos.json", "Mixed batch returns explicit saved/failed list and UI reconciles exactly once.", "Upload valid+invalid files, retry only failed one, and verify predictable count/order."),
("U08", "Medium", "UX defects — platform scope", "Four selectable marketplaces are silently omitted from sending", "All nine selected; dispatch filtering inspected", "Facebook, Grailed, Whatnot or Shopify selected", "Select All; compare catalog fillable flags and dispatch platform list.", "Clearly identify unavailable send support or implement the selected workflow.", "UI offers all nine; four have fillable false and are filtered without an explanatory unsupported state.", S+"services/marketplaces.py:64", "selected_fillable_marketplaces restricts to five while Settings labels selection as controlling Send.", "User reasonably expects every selected platform tested/sent; unavailable workflows hidden.", "all-marketplaces.json", "Selection UI accurately reflects supported send targets; unsupported selected target produces explicit blocker.", "Select each platform individually and verify either real saved form or a clear unsupported explanation."),
("T01", "Medium", "Test-coverage gaps", "Backend suite has a reproducible provider default expectation failure", "Full run 1 failure; individual retry also fails", "Current main and documented venv", "Run full pytest command, then exact failing node.", "Current provider contract and tests agree with isolated defaults.", "Expected gpt-5.5, received gpt-5.6-luna; 307 passed and one failed.", "vendoo-studio/server/tests/test_chatgpt_oauth.py:272", "Hardcoded test model expectation differs from effective configured/default model; test isolation/default contract needs resolution.", "CI-equivalent checks not green; does not alone establish broken provider connection.", "backend-tests.log; backend-failure-retest.log", "Pin expected contract or isolate settings correctly; rerun full suite and individual node.", "Confirm Settings shows the selected model before and after provider reconnect."),
("D01", "Low", "Documentation problems", "Doctor says Ready after identifying a startup-blocking occupied port", "1/1 initial doctor run", "Existing packaged Studio owns 4318", "Run doctor, then start.sh.", "Final readiness verdict distinguishes blocking port conflict and gives exact recovery.", "Doctor warns occupied port then prints Ready; start correctly refuses.", "vendoo-studio/scripts/doctor.sh:78", "Port warning does not affect final Ready at line 88.", "Confusing installation recovery; no stale process silently reused in this audit.", "doctor-initial.log; start-conflict.log", "Occupied-port fixture produces non-ready verdict/exit and correct recovery command.", "Run doctor beside an existing Studio process and verify final status is unambiguous."),
("D02", "Medium", "Documentation problems", "Canonical skill and reference template disagree on listing rules", "Multiple static conflicts", "Generation/validation consumes canonical skill and referenced template", "Compare price precision, title variants and description constraints.", "One explicit coherent contract for every platform.", "Skill requires whole dollars while template requires eBay/Etsy .99; description length/measurement placement and Etsy title differ.", "skills/list-this/SKILL.md:296", "Referenced template lines 16, 34, 102–115 has incompatible requirements with main skill/user fixture format.", "Cannot consistently validate or generate all outputs; fixes need a documented precedence decision.", "approved-studio-snapshot.json; canonical source files", "Contract tests assert a single price/title/description policy across prompts, schema and extension.", "Generate the same fixture through canonical skill and Studio; compare exact required formatting."),
]

lines = []
group = None
for fid, severity, category, title, rate, pre, steps, expected, actual, source, cause, risk, evidence, auto, manual in findings:
    if category != group:
        lines.append(f"\n### {category}\n")
        group = category
    path, lineno = source.rsplit(":", 1)
    evidence_links = []
    for name in evidence.split("; "):
        if (root / name).exists():
            evidence_links.append(f"[{name}](audit-artifacts-2026-09-13/{name})")
        else:
            evidence_links.append(name)
    lines.extend([
        f"\n#### {fid} — {title}\n",
        f"**Severity:** {severity}. **Component:** {category}. **Reproduction rate:** {rate}.",
        f"\n**Preconditions:** {pre}.\n\n**Exact reproduction:** {steps}",
        f"\n**Expected:** {expected}\n\n**Actual:** {actual}",
        f"\n**Evidence:** {'; '.join(evidence_links)}.",
        "\n**Console evidence:** See cited live console artifact where applicable; otherwise no finding-specific console record was captured. No absence-of-error claim is inferred.",
        "\n**Network evidence:** HTTP statuses are stated above for API probes; live job requests are represented by the cited event/readback records. A complete HAR was not captured.",
        "\n**Job-event evidence:** C08–C11, C21–C23 and fill-log findings use primary/ordinary-send final event artifacts. Isolated, UI-only and static findings did not require a real automation job.",
        f"\n**Likely root cause:** {cause}\n\n**Source:** [{path}:{lineno}]({path}#L{lineno}).",
        f"\n**User impact / data-loss or publication risk:** {risk}",
        f"\n**Recommended fix:** {expected} Address the cited cause; no fix was implemented during this audit.",
        f"\n**Automated regression:** {auto}\n\n**Manual regression:** {manual}\n",
    ])

report = repo / "FULL_SYSTEM_AUDIT.md"
text = report.read_text().replace("70 characters", "72 characters").replace("70-character", "72-character")
report.write_text(text + "\n".join(lines))
(root / "finding-index.json").write_text(json.dumps([{"id": f[0], "severity": f[1], "group": f[2], "title": f[3], "source": f[10]} for f in findings], indent=2))
print({"findings": len(findings), "report_bytes": report.stat().st_size})
