import { describe,it,expect } from "vitest";
import { MAX_BATCH_ITEMS,BATCH_STATUS,batchActions,batchReducer,createBatchItems,createInitialBatchState,createRestoredBatchItems,selectNextQueuedItem } from "./batchState.js";
const files=n=>Array.from({length:n},(_,i)=>({name:`${i}.png`}));
const items=n=>createBatchItems(files(n),{localIdFactory:(_,i)=>`local-${i}`,jobIdFactory:(_,i)=>i.toString(16).padStart(32,"0")});
describe("batch state",()=>{
 it("caps admission at ten and processes sequentially",()=>{let s=batchReducer(createInitialBatchState(),batchActions.admit(items(12)));expect(s.items).toHaveLength(MAX_BATCH_ITEMS);expect(selectNextQueuedItem(s).localId).toBe("local-0");s=batchReducer(s,batchActions.processing("local-0"));expect(selectNextQueuedItem(s)).toBeNull();});
 it("retry retains File but allocates a new job id",()=>{const [x]=items(1);let s=batchReducer(createInitialBatchState(),batchActions.admit([x]));s=batchReducer(s,batchActions.processing(x.localId));s=batchReducer(s,batchActions.failed(x.localId,"bad"));const before=s.items[0],next="f".repeat(32);s=batchReducer(s,batchActions.retry(x.localId,next));expect(s.items[0]).toMatchObject({file:before.file,clientJobId:next,status:BATCH_STATUS.QUEUED,error:null});});
 it("selects first success without stealing an existing ready selection",()=>{const xs=items(2);let s=batchReducer(createInitialBatchState(),batchActions.admit(xs));s=batchReducer(s,batchActions.processing("local-0"));s=batchReducer(s,batchActions.ready("local-0",{width:1,height:1}));expect(s.selectedLocalId).toBe("local-0");s=batchReducer(s,batchActions.processing("local-1"));s=batchReducer(s,batchActions.ready("local-1",{width:1,height:1}));expect(s.selectedLocalId).toBe("local-0");});
 it("hydrates restored jobs as non-uploadable display files",()=>{const restored=createRestoredBatchItems([{clientJobId:"a".repeat(32),localId:"recovered-a",file:{name:"photo.png",type:"image/png",size:123,lastModified:4},status:"ready",uploadable:false,backendWidth:200,backendHeight:100,editor:{threshold:3},createdAt:4,updatedAt:4}]);let s=createInitialBatchState(restored);expect(s.items[0]).toMatchObject({status:BATCH_STATUS.RESTORING,uploadable:false,backendWidth:200,file:{name:"photo.png",size:0}});s=batchReducer(s,batchActions.processing("recovered-a"));expect(s.items[0].status).toBe(BATCH_STATUS.RESTORING);s=batchReducer(s,batchActions.retry("recovered-a","b".repeat(32)));expect(s.items[0].clientJobId).toBe("a".repeat(32));s=batchReducer(s,batchActions.restoreReady("recovered-a",{width:200,height:100}));expect(s.selectedLocalId).toBe("recovered-a");});
});
