export const MAX_HEADER_BYTES = 256 * 1024;
export const MAX_IMAGE_PIXELS = 40_000_000;
export const THUMBNAIL_MAX_SIDE = 160;
export class ThumbnailError extends Error { constructor(code, message) { super(message); this.name = "ThumbnailError"; this.code = code; } }
const ascii = (b, o, n) => String.fromCharCode(...b.subarray(o, o + n));
const be16 = (b,o) => (b[o]<<8)|b[o+1];
const be32 = (b,o) => b[o]*0x1000000+(b[o+1]<<16)+(b[o+2]<<8)+b[o+3];
const le16 = (b,o) => b[o]|(b[o+1]<<8);
const le24 = (b,o) => b[o]|(b[o+1]<<8)|(b[o+2]<<16);
const le32 = (b,o) => (b[o]|(b[o+1]<<8)|(b[o+2]<<16)|(b[o+3]<<24))>>>0;
const valid = (format,width,height) => { if (!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1) throw new ThumbnailError("invalid_dimensions","Invalid image dimensions"); return {format,width,height}; };
function png(b) { if (b.length<8 || ascii(b,1,3)!=="PNG") return null; if (b.length<24 || ascii(b,12,4)!=="IHDR") throw new ThumbnailError("header_incomplete","PNG header incomplete"); return valid("png",be32(b,16),be32(b,20)); }
const SOF = new Set([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf]);
function jpeg(b) { if (b[0]!==0xff||b[1]!==0xd8) return null; let o=2; while(o+3<b.length){ while(b[o]===0xff)o++; const m=b[o++]; if(m===0xd9||m===0xda)break; if(m===0x00||m===0x01||(m>=0xd0&&m<=0xd8))continue; if(o+2>b.length)break; const n=be16(b,o); if(n<2)throw new ThumbnailError("invalid_header","Invalid JPEG segment"); if(SOF.has(m)){ if(o+7>b.length)break; return valid("jpeg",be16(b,o+5),be16(b,o+3)); } o+=n; } throw new ThumbnailError("header_incomplete","JPEG dimensions missing from bounded header"); }
function webp(b) { if(b.length<12||ascii(b,0,4)!=="RIFF"||ascii(b,8,4)!=="WEBP")return null; let o=12; while(o+8<=b.length){const type=ascii(b,o,4), size=le32(b,o+4), d=o+8; if(type==="VP8X"&&d+10<=b.length)return valid("webp",le24(b,d+4)+1,le24(b,d+7)+1); if(type==="VP8 "&&d+10<=b.length)return valid("webp",le16(b,d+6)&0x3fff,le16(b,d+8)&0x3fff); if(type==="VP8L"&&d+5<=b.length){const bits=le32(b,d+1);return valid("webp",(bits&0x3fff)+1,((bits>>>14)&0x3fff)+1);} o=d+size+(size%2); } throw new ThumbnailError("header_incomplete","WebP dimensions missing from bounded header"); }
export function parseImageDimensions(input){const b=input instanceof Uint8Array?input:new Uint8Array(input); const out=png(b)||jpeg(b)||webp(b); if(!out)throw new ThumbnailError("unsupported_format","Only PNG, JPEG, and WebP are supported"); return out;}
export function boundedThumbnailDimensions(width,height,maxSide=THUMBNAIL_MAX_SIDE){const scale=Math.min(1,maxSide/Math.max(width,height)); return {width:Math.max(1,Math.round(width*scale)),height:Math.max(1,Math.round(height*scale))};}
export async function readImageHeader(file,maxHeaderBytes=MAX_HEADER_BYTES){const end=Math.min(file.size,maxHeaderBytes); const bytes=new Uint8Array(await file.slice(0,end).arrayBuffer()); return parseImageDimensions(bytes);}
const toBlob = canvas => new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new ThumbnailError("encode_failed","Thumbnail encode failed")),"image/webp",0.82));
export async function createThumbnail(file, deps={}) { const dims=await readImageHeader(file,deps.maxHeaderBytes||MAX_HEADER_BYTES); if(dims.width>Math.floor((deps.maxPixels||MAX_IMAGE_PIXELS)/dims.height)) throw new ThumbnailError("image_too_large","Image exceeds pixel limit"); const target=boundedThumbnailDimensions(dims.width,dims.height,deps.maxSide||THUMBNAIL_MAX_SIDE); const decode=deps.createImageBitmapImpl||globalThis.createImageBitmap; const createCanvas=deps.createCanvas||((w,h)=>{const c=document.createElement("canvas");c.width=w;c.height=h;return c;}); const createUrl=deps.createObjectURL||URL.createObjectURL.bind(URL); const revokeUrl=deps.revokeObjectURL||URL.revokeObjectURL.bind(URL); let bitmap=null,url=null; try { bitmap=await decode(file,{imageOrientation:"from-image",resizeWidth:target.width,resizeHeight:target.height,resizeQuality:"high"}); const output=boundedThumbnailDimensions(bitmap.width,bitmap.height,deps.maxSide||THUMBNAIL_MAX_SIDE); const canvas=createCanvas(output.width,output.height); canvas.width=output.width;canvas.height=output.height; const context=canvas.getContext("2d"); if(!context)throw new ThumbnailError("canvas_unavailable","Canvas unavailable"); context.drawImage(bitmap,0,0,output.width,output.height); url=createUrl(await toBlob(canvas)); let revoked=false; return {url,width:output.width,height:output.height,revoke(){if(!revoked){revoked=true;revokeUrl(url);}}}; } catch(error){if(url)revokeUrl(url);throw error;} finally {bitmap?.close?.();} }
