"""baseline schema

Revision ID: eb12154c8bb2
Revises: 
Create Date: 2026-09-20 02:49:00.079753
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'eb12154c8bb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_field_schemas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('marketplace', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace', 'category_id')
    )
    op.create_table('category_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('marketplace', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('parent_path', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace', 'path')
    )
    op.create_table('category_schemas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('general_path', sa.String(), nullable=False),
    sa.Column('marketplace', sa.String(), nullable=False),
    sa.Column('category_path', sa.String(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('general_path', 'marketplace')
    )
    with op.batch_alter_table('category_schemas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_schemas_general_path'), ['general_path'], unique=False)

    op.create_table('category_tree_nodes',
    sa.Column('marketplace', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_leaf', sa.Boolean(), nullable=False),
    sa.Column('has_children', sa.Boolean(), nullable=False),
    sa.Column('children_loaded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('marketplace', 'category_id')
    )
    with op.batch_alter_table('category_tree_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_tree_nodes_path'), ['path'], unique=False)

    op.create_table('category_trees',
    sa.Column('marketplace', sa.String(), nullable=False),
    sa.Column('roots_loaded', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('marketplace')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('unsettled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_registry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('marketplace', sa.String(), nullable=False),
    sa.Column('category_path', sa.String(), nullable=True),
    sa.Column('normalized_label', sa.String(), nullable=False),
    sa.Column('control_type', sa.String(), nullable=True),
    sa.Column('is_dropdown', sa.Integer(), nullable=True),
    sa.Column('known_selectors', sa.JSON(), nullable=True),
    sa.Column('known_options', sa.JSON(), nullable=True),
    sa.Column('options_source', sa.String(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace', 'category_path', 'normalized_label', name='uq_field_registry_identity')
    )
    with op.batch_alter_table('field_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_registry_category_path'), ['category_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_registry_marketplace'), ['marketplace'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('approved_revision_id', sa.String(), nullable=False),
    sa.Column('listing_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('vendoo_item_id', sa.String(), nullable=True),
    sa.Column('vendoo_url', sa.String(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_revisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('listing_json', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('parent_revision_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_revisions_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('listings',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('current_revision_id', sa.String(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnostic_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('observation_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('collector_version', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('field_count', sa.Integer(), nullable=True),
    sa.Column('dropdown_count', sa.Integer(), nullable=True),
    sa.Column('dropdowns_with_options', sa.Integer(), nullable=True),
    sa.Column('live_dropdowns_with_options', sa.Integer(), nullable=True),
    sa.Column('total_dropdown_options', sa.Integer(), nullable=True),
    sa.Column('expanded_sections', sa.JSON(), nullable=True),
    sa.Column('headings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id')
    )
    with op.batch_alter_table('diagnostic_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnostic_runs_job_id'), ['job_id'], unique=False)

    op.create_table('fill_log_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('marketplace', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('selector', sa.String(), nullable=True),
    sa.Column('value_preview', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fill_log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fill_log_entries_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fill_log_entries_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fill_log_entries_marketplace'), ['marketplace'], unique=False)
        batch_op.create_index('ix_fill_log_job_step', ['job_id', 'step'], unique=False)

    op.create_table('job_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('step', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_events_job_id'), ['job_id'], unique=False)

    op.create_table('field_observations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('diagnostic_run_id', sa.String(), nullable=False),
    sa.Column('observation_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('label_sources', sa.JSON(), nullable=True),
    sa.Column('section_path', sa.JSON(), nullable=True),
    sa.Column('selector', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('control_type', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('control_id', sa.String(), nullable=True),
    sa.Column('placeholder', sa.String(), nullable=True),
    sa.Column('classes', sa.String(), nullable=True),
    sa.Column('is_dropdown', sa.Integer(), nullable=True),
    sa.Column('option_count', sa.Integer(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('options_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diagnostic_run_id'], ['diagnostic_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_observations_diagnostic_run_id'), ['diagnostic_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_observations_observation_id'), ['observation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_observations_observation_id'))
        batch_op.drop_index(batch_op.f('ix_field_observations_diagnostic_run_id'))

    op.drop_table('field_observations')
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_events_job_id'))

    op.drop_table('job_events')
    with op.batch_alter_table('fill_log_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_fill_log_job_step')
        batch_op.drop_index(batch_op.f('ix_fill_log_entries_marketplace'))
        batch_op.drop_index(batch_op.f('ix_fill_log_entries_job_id'))
        batch_op.drop_index(batch_op.f('ix_fill_log_entries_conversation_id'))

    op.drop_table('fill_log_entries')
    with op.batch_alter_table('diagnostic_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostic_runs_job_id'))

    op.drop_table('diagnostic_runs')
    op.drop_table('photos')
    op.drop_table('messages')
    op.drop_table('listings')
    with op.batch_alter_table('listing_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_revisions_conversation_id'))

    op.drop_table('listing_revisions')
    op.drop_table('jobs')
    with op.batch_alter_table('field_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_registry_marketplace'))
        batch_op.drop_index(batch_op.f('ix_field_registry_category_path'))

    op.drop_table('field_registry')
    op.drop_table('conversations')
    op.drop_table('category_trees')
    with op.batch_alter_table('category_tree_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_tree_nodes_path'))

    op.drop_table('category_tree_nodes')
    with op.batch_alter_table('category_schemas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_schemas_general_path'))

    op.drop_table('category_schemas')
    op.drop_table('category_nodes')
    op.drop_table('category_field_schemas')
    # ### end Alembic commands ###
